services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test
    environment:
      - XAUTH=${XAUTH:-/tmp/.docker.xauth} # This variable is set in the docker-x11-forward.sh
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH:-/tmp/.docker.xauth}
    volumes:
      - ${XAUTH:-/tmp/.docker.xauth}:${XAUTH:-/tmp/.docker.xauth}
    networks:
      - ros_network

networks:
  ros_network:
    driver: bridge
