services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test
    environment:
      - DISPLAY=host.docker.internal:10.0
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:ro
    networks:
      - ros_network
    #network_mode: host

networks:
  ros_network:
    driver: bridge
